services:
  scraper:
    build: .
    restart: always
    depends_on:
      - influxdb
      - vault

  influxdb:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=crypto_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-influx-token
    volumes:
      - influxdb-data:/var/lib/influxdb2

  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "my-root-token"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/file

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
      - prometheus

volumes:
  influxdb-data:
  grafana-data:
  vault-data: